trigger:
- main  # Or 'master' if that's your default branch

pool:
  name: Default  # Self-hosted agent pool

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.0.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: dotnet restore
  displayName: 'Restore Dependencies'

- script: dotnet build --configuration $(buildConfiguration) --no-restore
  displayName: 'Build Project'

#- script: dotnet test --configuration $(buildConfiguration) --no-build --verbosity normal
# displayName: 'Run Unit Tests'

- script: dotnet publish -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)
  displayName: 'Publish Application'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'aspnetcore-app'
    publishLocation: 'Container'
